# Collections
collections:
  collections_dir: collections

# Default permalink for main pages
permalink: "/:name/"

# Default values for front matter
defaults:
  - scope:
      path: {{ baseurl }}
      type: "posts"
    values:
      layout: "post"
      permalink: "/activity/posts/:year/:month/:title/"
  - scope:
      path: {{ baseurl }}
    values:
      layout: "default"

# GitHub Pages compatibility
title: "Jekyll Test"
url: "https://danielthefletch.github.io"
baseurl: "/portfolio"

# SASS configuration
sass:
  sass_dir: "/_sass"