# Collection settings
collections:
  posts:
    output: true
    permalink: "/activity/:collection/:year/:month/:title"
  projects:
    output: true
    permalink: "/:collection/:year/:title"

# Default permalink for main pages
permalink: "/:name/"

# Default values for front matter
defaults:
  - scope:
      path: {{ baseurl }}
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: {{ baseurl }}
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: {{ baseurl }}
    values:
      layout: "default"

# GitHub Pages compatibility
title: "Jekyll Test"
url: "https://danielthefletch.github.io"
baseurl: "/portfolio"

# SASS defaults
sass:
  sass_dir: "/_sass"

# Site-wide variables
subheading: "h2 fw-bold mb-1 pt-0"