# Development information

# Site metadata
author: "Daniel Fletcher"
date: "2023-11-19"
version: 1.0.0

# Contact information
contact:
  - name: "Email"
    link: "mailto:dfletcher-mail@proton.me"
    icon: "fa-solid fa-envelope"
  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/DanielTheFletch"
    icon: "fa-brands fa-linkedin"
  - name: "GitHub"
    link: "https://www.github.com/DanielTheFletch"
    icon: "fa-brands fa-github"
  - name: "Repository"
    link: "https://www.github.com/danielthefletch/portfolio"
    icon: "fa-solid fa-code-compare"